### ISSUE TITLE
Clarification on footer and header behavior

### ISSUE THREAD

**Issue by hrescak** [skayo/svelte-tiny-virtual-list#15]
Hello! I'm looking for some clarification on the footer and header behavior. When adding a footer and header, I'd expect it to
- not affect the overflow of the parent container. At this moment, when you add a footer and a header, there doesn't appear to be a way for the container to not show a scrollbar.
- the footer to be positioned immediately after the last element

Here's a [REPL](https://svelte.dev/repl/8435647ac9034eeea12626eb9fb198ad?version=3.46.6) illustrating the issue - I'd expect the footer to be visible right after the last number, and for there to be no scrollbar on the container. Is there a way currently to achieve such behavior?

Thanks!

**Comment by skayo** [comment]
The thing is, I've added the header/footer slots with invisible elements in mind - like my `svelte-infinite-loading` element. Nevertheless:

> * not affect the overflow of the parent container. At this moment, when you add a footer and a header, there doesn't appear to be a way for the container to not show a scrollbar.

This is indeed a weird issue/behaviour. I will look into it.

> * the footer to be positioned immediately after the last element

In your example the VirtualList has a height of 500px, and because it doesn't need all this space, the footer doesn't appear directly after the last element.

**Comment by skayo** [comment]
Fixed in 1d21bf9

**Comment by hrescak** [comment]
Thank you so much for the quick fix!
